// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvMDX4815tq5kjlH7U0uIkZgZdrGgR2lc',
    appId: '1:190169579590:web:f44c4e15425a1348b58a47',
    messagingSenderId: '190169579590',
    projectId: 'nearbystore-4a026',
    authDomain: 'nearbystore-4a026.firebaseapp.com',
    storageBucket: 'nearbystore-4a026.appspot.com',
    measurementId: 'G-W2DL0R8QKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4FyUhzaX-qoF9TEGHzfHvUyuK4e-ol94',
    appId: '1:190169579590:android:837e6797b20a6eddb58a47',
    messagingSenderId: '190169579590',
    projectId: 'nearbystore-4a026',
    storageBucket: 'nearbystore-4a026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA4Rn_10c0fNOON4fWfZ3Qd6VgQ1riY8I',
    appId: '1:190169579590:ios:794f29727d271545b58a47',
    messagingSenderId: '190169579590',
    projectId: 'nearbystore-4a026',
    storageBucket: 'nearbystore-4a026.appspot.com',
    iosBundleId: 'com.example.teamStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA4Rn_10c0fNOON4fWfZ3Qd6VgQ1riY8I',
    appId: '1:190169579590:ios:794f29727d271545b58a47',
    messagingSenderId: '190169579590',
    projectId: 'nearbystore-4a026',
    storageBucket: 'nearbystore-4a026.appspot.com',
    iosBundleId: 'com.example.teamStorage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvMDX4815tq5kjlH7U0uIkZgZdrGgR2lc',
    appId: '1:190169579590:web:194cd0ed1159cf31b58a47',
    messagingSenderId: '190169579590',
    projectId: 'nearbystore-4a026',
    authDomain: 'nearbystore-4a026.firebaseapp.com',
    storageBucket: 'nearbystore-4a026.appspot.com',
    measurementId: 'G-2Z0N919XDQ',
  );
}
